name: Build PR From Fork

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    if: | # check if PR opened from fork
      github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name || contains(github.head_ref, 'dependabot')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Build App
        uses: ./.github/actions/build
        with:
          NEXT_PUBLIC_ENV: 'prod'

      - name: Upload artifacts
        uses: ./.github/actions/upload-artifacts
